# -*- coding: utf-8 -*-
"""unidade_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e3EBZ5mREmAHOAbp8TggHGFMPK5VrTM8

# 📘 Módulo 1 – Introdução à Análise Descritiva de Dados (Parte 1)

Este roteiro é voltado para a compreensão inicial de como analisar dados de energia elétrica, com exemplos utilizando dados do Smart Campus UFCG.
---

## 🔌 1. Coleta e Armazenamento de Dados

O primeiro passo da análise de dados é entender **de onde os dados vêm** e **como são organizados**.

🧾 Neste curso, usaremos dados reais extraídos de sensores do campus, armazenados em planilhas. Nesse contexto, é necessário salientar que os dados utilizados nos exemplos são filtrados da planilha, ou seja, todos os gráficos vistos durante este roteiro são resultados da filtragem dos dados brutos de energia, advindos do Smart Campus UFCG.

📌 Os dados que vamos utilizar estão organizados da seguinte forma:

- **Data e Hora**
- **Consumo de Energia (kWh)**
- **Tensão (V)**
- **Corrente (A)**
- **Local do Medidor**

💻 Iremos usar os tópicos acima para dar exemplos e demonstrar de forma mais visual como compreender os conceitos apresentados.

---

## 🧩 2. Tipos de Variáveis

Vamos entender os **tipos de variáveis** presentes no nosso conjunto de dados.

- **Qualitativas Nominais**: categorizam sem ordem (ex: Local do Medidor, cor de olhos, estado civil, sexo)



Melhor indicação de uso: para classificar ou identificar grupos e útil em gráfico de barras ou tabelas de frequência

No exemplo abaixo dá para ver um gráfico de barras com a classificação de variável qualitativa nominal apenas pela descrição dos nomes dos Medidores.
"""

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# Dados simulados
medidores = ['Medidor LSD'] * 20 + ['Medidor CAA'] * 12 + ['Medidor Reitoria'] * 8
df = pd.DataFrame({'Nome': medidores})

# Gráfico com rótulo rotacionado
sns.set(style="whitegrid")
plt.figure(figsize=(8, 5))
df['Nome'].value_counts().plot(kind='bar', color='lightgreen', rot =0)
plt.title('Distribuição de Registros por Medidor (Qualitativa Nominal)')
plt.xlabel('Nome do Medidor')
plt.ylabel('Quantidade de Registros')
plt.tight_layout()
plt.show()

"""- **Qualitativas Ordinais**: categorizam com ordem ou grau(ex: Nível de Tensão: "Alta", "Média", "Baixa", grau de satisfação: bom, regular, ótimo)

Melhores indicações de uso: quando é importante comparar posições ou níveis. Também é muito utilizada em escalas de avaliação e rankeamento.
No exemplo abaixo podemos ver um gráfico parecido com o qualitativo nominal, porém, na sua classificação existe uma ordenação, ou melhor, existe um grau de satisfação entre as declarações das colunas.
"""

# Fatores de potência simulados
fp_valores = [0.88, 0.91, 0.94, 0.96, 0.98, 0.87, 0.89, 0.93, 0.95, 0.97]

# Classificar
def classificar_fp(fp):
    if fp < 0.90:
        return "Ruim"
    elif fp < 0.95:
        return "Regular"
    else:
        return "Bom"

df_fp = pd.DataFrame({'FP': fp_valores})
df_fp['Classificação'] = df_fp['FP'].apply(classificar_fp)

# Gráfico
ordem = ['Ruim', 'Regular', 'Bom']
plt.figure(figsize=(8, 5))
df_fp['Classificação'].value_counts().reindex(ordem).plot(kind='bar', color='lightgreen', rot = 0)
plt.title('Classificação do Fator de Potência (Qualitativa Ordinal)')
plt.xlabel('Classificação')
plt.ylabel('Frequência')
plt.tight_layout()
plt.show()

"""- **Quantitativas Discretas**: números contáveis e inteiros (ex: quantidade de eventos, número de filhos, número de atendimentos)

Usos mais comuns: quando o dado representa contagens, sendo muito comum em dados administrativos. Além disso, os gráficos mais indicados para esse tipo de dado são gráficos de colunas.
No gráfico abaixo é simples de identificar a comparação entre qual hora do dia obteve a maior quantidade de registros.
"""

# Dados fictícios de horários de leitura
horas = [0]*3 + [1]*5 + [2]*7 + [3]*6 + [4]*4 + [5]*3 + [6]*2
df_horas = pd.DataFrame({'Hora': horas})

# Gráfico
plt.figure(figsize=(8, 5))
df_horas['Hora'].value_counts().sort_index().plot(kind='bar', color='salmon', rot = 0)
plt.title('Número de Registros por Hora (Quantitativa Discreta)')
plt.xlabel('Hora do Dia')
plt.ylabel('Quantidade de Registros')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

"""- **Quantitativas Contínuas**: valores em uma escala contínua, ou seja, valores medidos que podem assumir qualquer valor dentro de um intervalo (ex: consumo em kWh, peso, altura, temperatura)

Uso mais comum: em análises estatísticas detalhadas como média e desvio padrão, em gráficos como histograma e distribuições.
No gráfico abaixo temos a junção de um histograma (barras verticais que mostram a frequência do consumo) e uma distribuição de densidade (linha suave sobre o histograma). Com isso, a história do gráfico é a estimativa contínua da densidade de probabilidade dos dados, dessa forma a linha indica onde os dados estão mais concentrados.
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Exemplo simples: consumo de energia em kWh
consumo = [12.3, 13.5, 11.2, 14.8, 12.9, 13.3, 11.9, 14.2, 13.0, 12.5]
df = pd.DataFrame({'Consumo (kWh)': consumo})

# Gráfico
plt.figure(figsize=(8, 5))
sns.histplot(df['Consumo (kWh)'], bins=5, kde=True, color='salmon')
plt.title('Distribuição do Consumo de Energia (Quantitativa Contínua)')
plt.xlabel('Consumo (kWh)')
plt.ylabel('Frequência')
plt.tight_layout()
plt.show()

"""## 🔍 3. Classificando as variáveis de Energia

identificando as variáveis do nosso dataset:

| Coluna             | Tipo de Variável                  |
|--------------------|-----------------------------------|
| Data e Hora        | Temporal                          |
| Local do Medidor   | Qualitativa Nominal               |
| Tensão (V)         | Quantitativa Contínua             |
| Corrente (A)       | Quantitativa Contínua             |
| Consumo (kWh)      | Quantitativa Contínua             |

## 🎯 4. Variáveis Qualitativas

Vamos observar a distribuição dos locais onde os medidores estão instalados:
"""

df['Local'].value_counts().plot(kind='bar', title='Distribuição dos Medidores por Local')

"""##🧮 5. Variáveis Quantitativas
a) Discretas
Variáveis discretas são contagens. Exemplo: número de registros por dia.
"""

df['Data'] = pd.to_datetime(df['Data e Hora']).dt.date
df.groupby('Data').size().plot(kind='line', title='Número de Registros por Dia')

"""b) Contínuas
Vamos analisar o consumo de energia:
"""

df['Consumo (kWh)'].plot(kind='hist', bins=30, title='Distribuição do Consumo (kWh)')

"""##📊 6. Distribuição de Frequência
Vamos estudar a distribuição de consumo:
"""

consumo_freq = pd.cut(df['Consumo (kWh)'], bins=5).value_counts().sort_index()
consumo_freq.plot(kind='bar', title='Distribuição de Frequência - Consumo (kWh)')